name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '8', '11', '15' ]
      fail-fast: false
    name: JAVA ${{ matrix.java }} OS ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
          arguments: build --stacktrace
      - name: Upload Test Results and Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: bitcoinj-core-test-results-jdk${{ matrix.java }}-${{ matrix.os }}
          path: |
            core/build/reports/tests/test/
            core/build/test-results/test/
